### PR TITLE
Fix #18 Rounding issue with limiting decimals for numbers near 100 million

### LINKED ISSUE #18: Rounding issue with limiting decimals for numbers near 100 million
I found some cases where `human-format` breaks, it seems to have an internal rounding error somewhere and it outputs the wrong number of digits:

> ```javascript
> humanFormat(111111111, { decimals: 1 })
> ```
> returns: `111.09999999999998 M`
> expected: `111.1 M`

> ```javascript
> humanFormat(100000001, { decimals: 1 })
> ```
> returns: `99.99999999999999 M`
> expected: `100.0 M`

### PR DESCRIPTION
**Pull request by james-rabbit**
This fixes a floating point formatting issue described in #18

### CODE REVIEW

**Comment by julien-f** [comment]
Thank you for your pull request but I found where the problem came from and I fixed the code.

**Comment by james-rabbit** [comment]
Thanks!

**Comment by james-rabbit** [comment]
Do you know when this will be available on npm?

**Comment by julien-f** [comment]
Sorry for that, it's available now :)

**Comment by james-rabbit** [comment]
Ah, great! Thank you.

**Pull request closed without merging**
